 name: trab_4_mobile
 description: A new Flutter project.

 publish_to: 'none'
 version: 1.0.0+1

 environment:
  sdk: ">=2.12.0 <3.0.0"

 dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1

  swipe_cards: ^0.1.0
  location: ^4.1.1
  google_maps_flutter: ^2.0.3
  flutter_google_places: 0.2.3
  date_field: ^2.0.1

  provider: ^5.0.0

  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.0
  firebase_auth: ^1.0.0
  image_picker: ^0.7.0-nullsafety

 dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

 flutter:
  uses-material-design: true

 assets:




